apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: knot
data:
  knot.conf: |
    server:
      listen: 0.0.0.0@53
      listen: ::@53
    zone:
    - domain: example.jp
      storage: /zones
      file: example.jp
    log:
      - target: stdout
        any: info

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zones
  labels:
    app: knot
data:
  example.jp: |
    $TTL 3600
    $ORIGIN example.jp.
    @	IN	SOA	ns01.example.jp. root.example.jp. 10 3600 900 1814400 900
    @	IN	NS localhost.
